homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
#introduction:

frontend:
config:
updater:
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
history:
ios:
sun:

panel_iframe:
  grafana:
    title: "Grafana"
    icon: mdi:chart-areaspline
    url: !secret grafana_url
  mdi_index:
    title: MDI Icons
    icon: mdi:vector-square
    url: !secret mdi_index_url

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

influxdb:
  host: 127.0.0.1
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password

tts:
  platform: google

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A14SREW-if00-port0
  debug:

#zwave:
#  usb_path: /dev/ttyACM0

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

camera:
  - platform: ffmpeg
    name: Camera Sannce
    input: !secret camera_input
    extra_arguments: -pred 1

zone:
  name: LIA
  latitude: !secret lia_lat
  longitude: !secret lia_long
  icon: mdi:code-braces

device_tracker: !include device_tracker.yaml
logger: !include logger.yaml
logbook: !include logbook.yaml
notify: !include notify.yaml
media_player: !include media_player.yaml
alert: !include alert.yaml

sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
group: !include_dir_merge_named group/
input_boolean: !include_dir_merge_named input_boolean/
input_select: !include_dir_merge_named input_select/
# input_slider: !include_dir_merge_named input_slider/
binary_sensor:
  - platform: ffmpeg_motion
    input: !secret ffmpeg_motion_input
    reset: 60

## TEST AREA ##
  # - platform: template 
  #   sensors:
  #     movement:
  #       value_template: "{{ states.switch.motion_sensor.state == 'on' }}"
  #       device_class: motion
  #     door:
  #       value_template: "{{ states.switch.door.state == 'on' }}" 
  #       device_class: opening
#shell_command: !include_dir_merge_named shell_command


