#https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sensor/devices_states.yaml
- platform: template
  sensors:
      isa:
        friendly_name: 'Isa'
        value_template: "{{ 'Home' if is_state('input_boolean.isabella_home', 'on') else 'Away' }}"
      stefan:
        friendly_name: 'Stefan'
        value_template: "{{ 'Home' if is_state('input_boolean.stefan_home', 'on') else 'Away' }}"

      nas:
        friendly_name: 'Synology NAS'
        value_template: "{{ 'Online' if is_state('device_tracker.0011325962fb', 'home') else 'Offline' }}"
      netgear_router:
        friendly_name: 'Netgear Router'
        value_template: "{{ 'Online' if is_state('device_tracker.204e7f4bf81b', 'home') else 'Offline' }}"
      shield:
        friendly_name: 'NVidia Shield'
        value_template: "{{ 'Online' if is_state('device_tracker.android8e3893d2d746d835', 'home') else 'Offline' }}"
      shield_2:
        friendly_name: 'NVidia Shield 2'
        value_template: "{{ 'Online' if is_state('device_tracker.shield', 'home') else 'Offline' }}"
      chromecast:
        friendly_name: 'Chromecast'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'Offline' }}"
      stefan_computer:
        friendly_name: 'Stefans dator'
        value_template: "{{ 'Online' if is_state('device_tracker.grimsan55', 'home') else 'Offline' }}"
      isa_computer:
        friendly_name: 'Isas dator'
        value_template: "{{ 'Online' if is_state('device_tracker.isa', 'home') else 'Offline' }}"
      printer:
        friendly_name: 'Skrivare'
        value_template: "{{ 'Online' if is_state('device_tracker.hp16eece', 'home') else 'Offline' }}"
      ipad:
        friendly_name: 'iPad'
        value_template: "{{ 'Online' if is_state('device_tracker.paddan', 'home') else 'Offline' }}"
      hue_hub:
        friendly_name: 'Philips Hue Hub'
        value_template: "{{ 'Online' if is_state('device_tracker.philipshue', 'home') else 'Offline' }}"
      asus_router:
        friendly_name: 'Asus Router'
        value_template: "{{ 'Online' if is_state('device_tracker.routerasuscom', 'home') else 'Offline' }}"
      tivo:
        friendly_name: 'TIVO'
        value_template: "{{ 'Online' if is_state('device_tracker.tivoe800d5bf09d5729', 'home') else 'Offline' }}"