#mdi:sleep mdi:sleep_off

# maybe automation tv and pc off and time is past 00 - stefan asleep


- alias: All asleep
  trigger:
    - platform: time
      minutes: '/15'
      seconds: 00
  condition:
    condition: and
    conditions:
      ## Has to be between 22 and 06
      - condition: time
        after: '22:00:00'
        before: '06:00:00'
      ## Someone has to be home
      - condition: state
        entity_id: group.persons
        state: 'home'
      ## No movement detected
      # - condition: state
      #   entity_id: sensor.upstairs_hallway_movement
      #   state: 'No movement'
      # - condition: state
      #   entity_id: sensor.passage_movement
      #   state: 'No movement'
      ## Bedroom light has to be off
      - condition: state
        entity_id: light.isa_ceiling_lamp
        state: 'off'
      - condition: state
        entity_id: input_select.day_mode
        state: Evening

      ## All computers off (not reliable, due to sometimes leaving on, how to fix?)
      - condition: state
        entity_id: sensor.isa_computer
        state: Offline
      - condition: state
        entity_id: sensor.isa_laptop
        state: Offline
      - condition: state
        entity_id: sensor.stefan_computer
        state: Offline

      # - condition: state
      #   entity_id: sensor.isabellas_iphone_6s_battery_state
      #   state: Charging
      #   ## fel namn?
      # - condition: state
      #   entity_id: sensor.igrims_battery_state
      #   state: Charging

      ## Tv-system bottenvåning avstängt
      ## group.media_player_view?
      - condition: state
        entity_id: sensor.movie_system
        state: Offline
      - condition: state
        entity_id: sensor.samsung65
        state: Offline
      ## Tv sovrum avstängd
      - condition: state
        entity_id: sensor.samsung49
        state: Offline
      #   ## försöker täcka alla olika states för shield
      # - condition: or
      #   conditions:
      #   - condition: state
      #     entity_id: media_player.plex_shield
      #     state: idle
      #   - condition: state
      #     entity_id: media_player.plex_shield
      #     state: 'off'
      #   - condition: state
      #     entity_id: media_player.shield
      #     state: idle
      #   - condition: state
      #     entity_id: media_player.shield
      #     state: 'off'
      #   - condition: state
      #     entity_id: sensor.shield
      #     state: Offline
      #   - condition: state
      #     entity_id: sensor.shield_2
      #     state: Offline

  action:
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: 'It seems like everyone is asleep'
        title: 'Good night!'
    - service: input_select.select_option
      data:
        entity_id: input_select.day_mode
        option: Night