###################################
##  Set to evening               ##
###################################

- alias: 'Day mode to evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:45:00'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.day_mode
        option: Evening

###################################
##  Set to morning               ##
###################################

- alias: 'Day mode to morning'
  trigger:
    - platform: sun
      event: sunrise

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.day_mode
        option: Morning

###################################
##  Set to day                   ##
###################################

- alias: 'Day mode to day'
  trigger:
    - platform: time
      at: "08:00:00"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.day_mode
        option: Day

## TODO: Set to night at input_boolean goodnight