# sensor.washer_plug_power
- alias: Set washing machine active when power detected
  trigger:
    platform: state
    entity_id: sensor.washer
    from: 'True'
    to: 'False'
  # condition:
  #   condition: or
  #   conditions:
  #     - condition: state
  #       entity_id: sensor.washing_machine_status
  #       state: Idle
  #     - condition: state
  #       entity_id: sensor.washing_machine_status
  #       state: Clean
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Running

- alias: Set washing machine clean after timeout
  trigger:
    platform: state
    entity_id: sensor.washer
    from: 'False'
    to: 'True'
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Clean

# - alias: Set washing machine dirty when door opens
#   trigger:
#     # I've setup a template sensor to change make the binary_sensor report open and closed
#     # instead of 1 and 0
#     - platform: state
#       entity_id: input_select.washingmachine_door_status
#       to: 'Open'
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: input_select.washing_machine_status
#         state: Clean
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.washing_machine_status
#         option: Idle



############################################################################




# - alias: 'Washer Start'
#   trigger:
#     platform: state
#     entity_id: sensor.washer
#     from: 'True'
#     to: 'False'
#   action:
#     - service: input_boolean.turn_on
#       entity_id: input_boolean.washer_in_use
#     - service: notify.ios_isabellas_iphone_6s
#       data:
#         title: 'Tvätten har satts igång'
#         message: 'Wee'

# - alias: 'Washer Done'
#   trigger:
#     platform: state
#     entity_id: sensor.washer
#     from: 'False'
#     to: 'True'
#     for:
#       minutes: 10
#   condition:
#       condition: state
#       entity_id: input_boolean.washer_in_use
#       state: 'on'
#   action:
#     - service: notify.ios_isabellas_iphone_6s
#       data:
#         title: 'Tvätten är klar.'
#         message: 'Lägg in i torktumlaren och häng upp!'
#       ## change to separate automation for each person to get notification when home        
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.washer_in_use