- alias: Update Hass notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.pushbullet
    data_template: 
      title: 'New Home Assistant Release'
      target: 'device/isadator'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."