# test with door trigger for presence (if door is not opened I cannot have left) - seems to be working
- alias: 'Isa away'
  trigger:
    - platform: state
      entity_id: group.isabella
      state: 'not_home'
      for:
        minutes: 10
  # door must have been opened in the last 20 minutes to be reported as away
  condition:
    condition: state
    entity_id: input_boolean.front_door
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.isabella_home
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Du är nu rapporterad som inte hemma.'
        message: 'Inte hemma'

## Isa is set as home as soon as group.isabella is set as home

- alias: 'Isa Home'
  condition:
    condition: state
    entity_id: input_boolean.isabella_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: group.isabella
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.isabella_home
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Du är nu rapporterad som hemma.'
        message: 'Hemma'