- alias: 'Isa Away'
  condition:
    condition: state
    entity_id: input_boolean.isabella_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.isabellas_iphone_6s
      state: 'not_home'
      for:
        minutes: 10
    - platform: state
      entity_id: device_tracker.isabelliphone6s
      state: 'not_home'     
      for:
        minutes: 10  
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.isabella_home

- alias: 'Isa Home'
  condition:
    condition: state
    entity_id: input_boolean.isabella_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.isabellas_iphone_6s
      state: 'home' 
    - platform: state
      entity_id: device_tracker.isabelliphone6s
      state: 'home'       
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.isabella_home