# test with door trigger for presence (if door is not opened I cannot have left) - seems to be working
- alias: 'Stefan away'
  trigger:
    - platform: state
      # entity_id: group.stefan
      entity_id: device_tracker.stefan_iphone_7
      to: 'not_home'
  action:
    # - service: homeassistant.turn_off
    #   entity_id: input_boolean.stefan_home
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Stefan är nu rapporterad som inte hemma.'
        message: 'Inte hemma'

- alias: 'Stefan Home'
  trigger:
    - platform: state
      entity_id: device_tracker.stefan_iphone_7
      to: 'home'     
  action:
    # - service: homeassistant.turn_on
    #   entity_id: input_boolean.stefan_home
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Stefan är nu rapporterad som hemma.'
        message: 'Hemma'