## Every hour between 10 and 17 check if no one is home.
## If no one is home and you havent already vacuumed today, switch on the roomba and set vacuumed today to on.

- alias: 'Vacuum when everyone is away'
  trigger:
    platform: time
    minutes: 5
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.persons
        state: 'not_home'
      - condition: time
        after: '09:00:00'
        before: '17:00:00'
      - condition: state
        entity_id: input_boolean.vacuumed_today
        state: 'off'
  action:
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: 'Vacuum now?'
        title: 'No one seems to be at home'
        data:
          push:
            badge: 0
            category: "VACUUM"


- alias: Vacuum now
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: VACUUM_NOW
  action:
    - service: homeassistant.turn_on
      entity_id: switch.roomba
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacuumed_today
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: 'Telling the Roomba to start vacuuming'

- alias: Vacuum snoozed
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: VACUUM_LATER
  action:
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: 'I will check again next hour'
        title: 'Not vacuuming right now'

## Reset the vacuumed today check each night
- alias: 'Reset vaccuming boolean'
  trigger:
    platform: time
    at: '00:01:00' ## change to at after update hass
  condition:
    condition: state
    entity_id: input_boolean.vacuumed_today
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacuumed_today
    - service: homeassistant.turn_off
      entity_id: switch.roomba
# input_boolean.vacuumed_today