homeassistant:
  customize:
    sensor.upstairs_litter_box_visits:
      icon: mdi:poop

#-------------------------------------------

#-------------------------------------------

switch:
  - platform: mqtt
    name: "UpstairsLitterBox"
    state_topic: "UpstairsLitterBox/Button/state"
    command_topic: "UpstairsLitterBox/gpio/13"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "UpstairsLitterBoxBlueLed"
    state_topic: "UpstairsLitterBox/blueled/state"
    command_topic: "UpstairsLitterBox/gpio/15"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "UpstairsLitterBoxGreenLed"
    state_topic: "UpstairsLitterBox/greenled/state"
    command_topic: "UpstairsLitterBox/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "UpstairsLitterBoxRedLed"
    state_topic: "UpstairsLitterBox/redled/state"
    command_topic: "UpstairsLitterBox/gpio/02"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

#-------------------------------------------

binary_sensor:
  - platform: mqtt
    name: "Upstairs Litter Box Pir"
    state_topic: "UpstairsLitterBox/pir/state"
    command_topic: "UpstairsLitterBox/gpio/14"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

#-------------------------------------------

sensor:
  - platform: mqtt
    state_topic: "dummy/upstairslitterbox/count"
    name: Upstairs Litter Box Visits
    unit_of_measurement: "visits"

#-------------------------------------------

automation:
  - alias: Set Litter Box Sensor To Zero On Start
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: python_script.ulitter_reset
    
    
  - alias: Count visits to upstairs litter box
    trigger:
      - platform: state
        entity_id: binary_sensor.upstairs_litter_box_pir
        to: 'on'
    condition:
    - condition: template
      value_template: >
        {% if states.automation.count_visits_to_upstairs_litter_box.last_triggered is not none %}
          {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.count_visits_to_upstairs_litter_box.attributes.last_triggered) | int > 300 %} true {% else %} false
          {% endif %}
        {% else %}
        false
        {% endif %}
    action:
      - service: python_script.ulitter_counter
      - service: homeassistant.turn_on
        entity_id: switch.upstairslitterboxblueled
      - delay: '00:00:30'
      - service: homeassistant.turn_off
        entity_id: switch.upstairslitterboxblueled


  - alias: Send notification when upstairs litter box is used more than three times
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_litter_box_visits
        above: '2'
      - platform: state
        entity_id: device_tracker.isabellas_iphone_6s
        to: 'home'
        for:
          minutes: 10
    condition:
      condition: and
      conditions:
        - condition: time
          after: '07:00:00'
          before: '23:00:00'
        - condition: state
          entity_id: device_tracker.isabellas_iphone_6s
          state: 'home'
        - condition: numeric_state
          entity_id: sensor.upstairs_litter_box_visits
          above: '2'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.upstairslitterboxredled
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Time to clean!'
          message: 'More than three visits to upstairs litter box'

  # Input select for three different litter box modes? Idle, In use and Cleaning mode. When in cleaning mode don't count as visit.
  # also make sensor for total amount of visits on box(es)


  - alias: Reset litter box visit counter
    trigger:
      - platform: state
        entity_id: switch.upstairslitterbox
    action:
      - service: python_script.ulitter_reset
      - service: homeassistant.turn_off
        entity_id: switch.upstairslitterboxredled
      - service: homeassistant.turn_on
        entity_id: switch.upstairslitterboxgreenled
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.upstairslitterboxgreenled